/**
 * ConfigCat Public Management API
 * **Base API URL**: https://test-api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://test-api.configcat.com/swagger).  The purpose of this API is to access the ConfigCat platform programmatically.  You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.   The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  and JSON+HAL format. Do not use this API for accessing and evaluating feature flag values. Use the [SDKs instead](https://configcat.com/docs/sdk-reference/overview).   # OpenAPI Specification  The complete specification is publicly available here: [swagger.json](v1/swagger.json).  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 
 *
 * The version of the OpenAPI document: v1
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccessType } from './accessType';
import { CreateOrUpdateEnvironmentAccessModel } from './createOrUpdateEnvironmentAccessModel';
import { EnvironmentAccessType } from './environmentAccessType';

export class UpdatePermissionGroupRequest {
    'name'?: string | null;
    'canManageMembers'?: boolean | null;
    'canCreateOrUpdateConfig'?: boolean | null;
    'canDeleteConfig'?: boolean | null;
    'canCreateOrUpdateEnvironment'?: boolean | null;
    'canDeleteEnvironment'?: boolean | null;
    'canCreateOrUpdateSetting'?: boolean | null;
    'canTagSetting'?: boolean | null;
    'canDeleteSetting'?: boolean | null;
    'canCreateOrUpdateTag'?: boolean | null;
    'canDeleteTag'?: boolean | null;
    'canManageWebhook'?: boolean | null;
    'canUseExportImport'?: boolean | null;
    'canManageProductPreferences'?: boolean | null;
    'canManageIntegrations'?: boolean | null;
    'canViewSdkKey'?: boolean | null;
    'canRotateSdkKey'?: boolean | null;
    'canViewProductStatistics'?: boolean | null;
    'canViewProductAuditLog'?: boolean | null;
    'canCreateOrUpdateSegments'?: boolean | null;
    'canDeleteSegments'?: boolean | null;
    'accessType'?: AccessType;
    'newEnvironmentAccessType'?: EnvironmentAccessType;
    'environmentAccesses'?: Array<CreateOrUpdateEnvironmentAccessModel> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "canManageMembers",
            "baseName": "canManageMembers",
            "type": "boolean"
        },
        {
            "name": "canCreateOrUpdateConfig",
            "baseName": "canCreateOrUpdateConfig",
            "type": "boolean"
        },
        {
            "name": "canDeleteConfig",
            "baseName": "canDeleteConfig",
            "type": "boolean"
        },
        {
            "name": "canCreateOrUpdateEnvironment",
            "baseName": "canCreateOrUpdateEnvironment",
            "type": "boolean"
        },
        {
            "name": "canDeleteEnvironment",
            "baseName": "canDeleteEnvironment",
            "type": "boolean"
        },
        {
            "name": "canCreateOrUpdateSetting",
            "baseName": "canCreateOrUpdateSetting",
            "type": "boolean"
        },
        {
            "name": "canTagSetting",
            "baseName": "canTagSetting",
            "type": "boolean"
        },
        {
            "name": "canDeleteSetting",
            "baseName": "canDeleteSetting",
            "type": "boolean"
        },
        {
            "name": "canCreateOrUpdateTag",
            "baseName": "canCreateOrUpdateTag",
            "type": "boolean"
        },
        {
            "name": "canDeleteTag",
            "baseName": "canDeleteTag",
            "type": "boolean"
        },
        {
            "name": "canManageWebhook",
            "baseName": "canManageWebhook",
            "type": "boolean"
        },
        {
            "name": "canUseExportImport",
            "baseName": "canUseExportImport",
            "type": "boolean"
        },
        {
            "name": "canManageProductPreferences",
            "baseName": "canManageProductPreferences",
            "type": "boolean"
        },
        {
            "name": "canManageIntegrations",
            "baseName": "canManageIntegrations",
            "type": "boolean"
        },
        {
            "name": "canViewSdkKey",
            "baseName": "canViewSdkKey",
            "type": "boolean"
        },
        {
            "name": "canRotateSdkKey",
            "baseName": "canRotateSdkKey",
            "type": "boolean"
        },
        {
            "name": "canViewProductStatistics",
            "baseName": "canViewProductStatistics",
            "type": "boolean"
        },
        {
            "name": "canViewProductAuditLog",
            "baseName": "canViewProductAuditLog",
            "type": "boolean"
        },
        {
            "name": "canCreateOrUpdateSegments",
            "baseName": "canCreateOrUpdateSegments",
            "type": "boolean"
        },
        {
            "name": "canDeleteSegments",
            "baseName": "canDeleteSegments",
            "type": "boolean"
        },
        {
            "name": "accessType",
            "baseName": "accessType",
            "type": "AccessType"
        },
        {
            "name": "newEnvironmentAccessType",
            "baseName": "newEnvironmentAccessType",
            "type": "EnvironmentAccessType"
        },
        {
            "name": "environmentAccesses",
            "baseName": "environmentAccesses",
            "type": "Array<CreateOrUpdateEnvironmentAccessModel>"
        }    ];

    static getAttributeTypeMap() {
        return UpdatePermissionGroupRequest.attributeTypeMap;
    }
}

