/* tslint:disable */
/* eslint-disable */
/**
 * ConfigCat Public Management API
 * The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 
 *
 * The version of the OpenAPI document: v1
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CreatePermissionGroupRequest } from '../model';
// @ts-ignore
import { PermissionGroupModel } from '../model';
// @ts-ignore
import { UpdatePermissionGroupRequest } from '../model';
/**
 * PermissionGroupsApi - axios parameter creator
 * @export
 */
export const PermissionGroupsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint creates a new Permission Group in a specified Product  identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
         * @summary Create Permission Group
         * @param {string} productId The identifier of the Product.
         * @param {CreatePermissionGroupRequest} createPermissionGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPermissionGroup: async (productId: string, createPermissionGroupRequest: CreatePermissionGroupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('createPermissionGroup', 'productId', productId)
            // verify required parameter 'createPermissionGroupRequest' is not null or undefined
            assertParamExists('createPermissionGroup', 'createPermissionGroupRequest', createPermissionGroupRequest)
            const localVarPath = `/v1/products/{productId}/permissions`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPermissionGroupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint removes a Permission Group identified by the `permissionGroupId` parameter.
         * @summary Delete Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePermissionGroup: async (permissionGroupId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'permissionGroupId' is not null or undefined
            assertParamExists('deletePermissionGroup', 'permissionGroupId', permissionGroupId)
            const localVarPath = `/v1/permissions/{permissionGroupId}`
                .replace(`{${"permissionGroupId"}}`, encodeURIComponent(String(permissionGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint returns the metadata of a Permission Group  identified by the `permissionGroupId`.
         * @summary Get Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPermissionGroup: async (permissionGroupId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'permissionGroupId' is not null or undefined
            assertParamExists('getPermissionGroup', 'permissionGroupId', permissionGroupId)
            const localVarPath = `/v1/permissions/{permissionGroupId}`
                .replace(`{${"permissionGroupId"}}`, encodeURIComponent(String(permissionGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint returns the list of the Permission Groups that belongs to the given Product identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
         * @summary List Permission Groups
         * @param {string} productId The identifier of the Product.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPermissionGroups: async (productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('getPermissionGroups', 'productId', productId)
            const localVarPath = `/v1/products/{productId}/permissions`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint updates a Permission Group identified by the `permissionGroupId` parameter.
         * @summary Update Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {UpdatePermissionGroupRequest} updatePermissionGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePermissionGroup: async (permissionGroupId: number, updatePermissionGroupRequest: UpdatePermissionGroupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'permissionGroupId' is not null or undefined
            assertParamExists('updatePermissionGroup', 'permissionGroupId', permissionGroupId)
            // verify required parameter 'updatePermissionGroupRequest' is not null or undefined
            assertParamExists('updatePermissionGroup', 'updatePermissionGroupRequest', updatePermissionGroupRequest)
            const localVarPath = `/v1/permissions/{permissionGroupId}`
                .replace(`{${"permissionGroupId"}}`, encodeURIComponent(String(permissionGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePermissionGroupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PermissionGroupsApi - functional programming interface
 * @export
 */
export const PermissionGroupsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PermissionGroupsApiAxiosParamCreator(configuration)
    return {
        /**
         * This endpoint creates a new Permission Group in a specified Product  identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
         * @summary Create Permission Group
         * @param {string} productId The identifier of the Product.
         * @param {CreatePermissionGroupRequest} createPermissionGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPermissionGroup(productId: string, createPermissionGroupRequest: CreatePermissionGroupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PermissionGroupModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPermissionGroup(productId, createPermissionGroupRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PermissionGroupsApi.createPermissionGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint removes a Permission Group identified by the `permissionGroupId` parameter.
         * @summary Delete Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePermissionGroup(permissionGroupId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePermissionGroup(permissionGroupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PermissionGroupsApi.deletePermissionGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint returns the metadata of a Permission Group  identified by the `permissionGroupId`.
         * @summary Get Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPermissionGroup(permissionGroupId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PermissionGroupModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPermissionGroup(permissionGroupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PermissionGroupsApi.getPermissionGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint returns the list of the Permission Groups that belongs to the given Product identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
         * @summary List Permission Groups
         * @param {string} productId The identifier of the Product.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPermissionGroups(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PermissionGroupModel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPermissionGroups(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PermissionGroupsApi.getPermissionGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint updates a Permission Group identified by the `permissionGroupId` parameter.
         * @summary Update Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {UpdatePermissionGroupRequest} updatePermissionGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePermissionGroup(permissionGroupId: number, updatePermissionGroupRequest: UpdatePermissionGroupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PermissionGroupModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePermissionGroup(permissionGroupId, updatePermissionGroupRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PermissionGroupsApi.updatePermissionGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PermissionGroupsApi - factory interface
 * @export
 */
export const PermissionGroupsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PermissionGroupsApiFp(configuration)
    return {
        /**
         * This endpoint creates a new Permission Group in a specified Product  identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
         * @summary Create Permission Group
         * @param {string} productId The identifier of the Product.
         * @param {CreatePermissionGroupRequest} createPermissionGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPermissionGroup(productId: string, createPermissionGroupRequest: CreatePermissionGroupRequest, options?: any): AxiosPromise<PermissionGroupModel> {
            return localVarFp.createPermissionGroup(productId, createPermissionGroupRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint removes a Permission Group identified by the `permissionGroupId` parameter.
         * @summary Delete Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePermissionGroup(permissionGroupId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deletePermissionGroup(permissionGroupId, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint returns the metadata of a Permission Group  identified by the `permissionGroupId`.
         * @summary Get Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPermissionGroup(permissionGroupId: number, options?: any): AxiosPromise<PermissionGroupModel> {
            return localVarFp.getPermissionGroup(permissionGroupId, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint returns the list of the Permission Groups that belongs to the given Product identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
         * @summary List Permission Groups
         * @param {string} productId The identifier of the Product.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPermissionGroups(productId: string, options?: any): AxiosPromise<Array<PermissionGroupModel>> {
            return localVarFp.getPermissionGroups(productId, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint updates a Permission Group identified by the `permissionGroupId` parameter.
         * @summary Update Permission Group
         * @param {number} permissionGroupId The identifier of the Permission Group.
         * @param {UpdatePermissionGroupRequest} updatePermissionGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePermissionGroup(permissionGroupId: number, updatePermissionGroupRequest: UpdatePermissionGroupRequest, options?: any): AxiosPromise<PermissionGroupModel> {
            return localVarFp.updatePermissionGroup(permissionGroupId, updatePermissionGroupRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PermissionGroupsApi - object-oriented interface
 * @export
 * @class PermissionGroupsApi
 * @extends {BaseAPI}
 */
export class PermissionGroupsApi extends BaseAPI {
    /**
     * This endpoint creates a new Permission Group in a specified Product  identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
     * @summary Create Permission Group
     * @param {string} productId The identifier of the Product.
     * @param {CreatePermissionGroupRequest} createPermissionGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PermissionGroupsApi
     */
    public createPermissionGroup(productId: string, createPermissionGroupRequest: CreatePermissionGroupRequest, options?: RawAxiosRequestConfig) {
        return PermissionGroupsApiFp(this.configuration).createPermissionGroup(productId, createPermissionGroupRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint removes a Permission Group identified by the `permissionGroupId` parameter.
     * @summary Delete Permission Group
     * @param {number} permissionGroupId The identifier of the Permission Group.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PermissionGroupsApi
     */
    public deletePermissionGroup(permissionGroupId: number, options?: RawAxiosRequestConfig) {
        return PermissionGroupsApiFp(this.configuration).deletePermissionGroup(permissionGroupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint returns the metadata of a Permission Group  identified by the `permissionGroupId`.
     * @summary Get Permission Group
     * @param {number} permissionGroupId The identifier of the Permission Group.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PermissionGroupsApi
     */
    public getPermissionGroup(permissionGroupId: number, options?: RawAxiosRequestConfig) {
        return PermissionGroupsApiFp(this.configuration).getPermissionGroup(permissionGroupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint returns the list of the Permission Groups that belongs to the given Product identified by the `productId` parameter, which can be obtained from the [List Products](#operation/get-products) endpoint.
     * @summary List Permission Groups
     * @param {string} productId The identifier of the Product.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PermissionGroupsApi
     */
    public getPermissionGroups(productId: string, options?: RawAxiosRequestConfig) {
        return PermissionGroupsApiFp(this.configuration).getPermissionGroups(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint updates a Permission Group identified by the `permissionGroupId` parameter.
     * @summary Update Permission Group
     * @param {number} permissionGroupId The identifier of the Permission Group.
     * @param {UpdatePermissionGroupRequest} updatePermissionGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PermissionGroupsApi
     */
    public updatePermissionGroup(permissionGroupId: number, updatePermissionGroupRequest: UpdatePermissionGroupRequest, options?: RawAxiosRequestConfig) {
        return PermissionGroupsApiFp(this.configuration).updatePermissionGroup(permissionGroupId, updatePermissionGroupRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

