/* tslint:disable */
/* eslint-disable */
/**
 * ConfigCat Public Management API
 * The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 
 *
 * The version of the OpenAPI document: v1
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { StatisticsV2Model } from '../model';
/**
 * UsageQuotaApi - axios parameter creator
 */
export const UsageQuotaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint returns the current usage and quota information for an Organization. You can optionally filter the result by Product using the `productId` query parameter.  The response includes monthly aggregate values, detailed request statistics, and quota limits used to monitor consumption and over-limit conditions.
         * @summary Get usage and quota
         * @param {string} organizationId The identifier of the Organization.
         * @param {string} [productId] The identifier of the Product to filter statistics for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationUsageAndQuota: async (organizationId: string, productId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('getOrganizationUsageAndQuota', 'organizationId', organizationId)
            const localVarPath = `/v1/organizations/{organizationId}/usage-and-quota`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (productId !== undefined) {
                localVarQueryParameter['productId'] = productId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsageQuotaApi - functional programming interface
 */
export const UsageQuotaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsageQuotaApiAxiosParamCreator(configuration)
    return {
        /**
         * This endpoint returns the current usage and quota information for an Organization. You can optionally filter the result by Product using the `productId` query parameter.  The response includes monthly aggregate values, detailed request statistics, and quota limits used to monitor consumption and over-limit conditions.
         * @summary Get usage and quota
         * @param {string} organizationId The identifier of the Organization.
         * @param {string} [productId] The identifier of the Product to filter statistics for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationUsageAndQuota(organizationId: string, productId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatisticsV2Model>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganizationUsageAndQuota(organizationId, productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageQuotaApi.getOrganizationUsageAndQuota']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsageQuotaApi - factory interface
 */
export const UsageQuotaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsageQuotaApiFp(configuration)
    return {
        /**
         * This endpoint returns the current usage and quota information for an Organization. You can optionally filter the result by Product using the `productId` query parameter.  The response includes monthly aggregate values, detailed request statistics, and quota limits used to monitor consumption and over-limit conditions.
         * @summary Get usage and quota
         * @param {string} organizationId The identifier of the Organization.
         * @param {string} [productId] The identifier of the Product to filter statistics for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationUsageAndQuota(organizationId: string, productId?: string, options?: RawAxiosRequestConfig): AxiosPromise<StatisticsV2Model> {
            return localVarFp.getOrganizationUsageAndQuota(organizationId, productId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsageQuotaApi - object-oriented interface
 */
export class UsageQuotaApi extends BaseAPI {
    /**
     * This endpoint returns the current usage and quota information for an Organization. You can optionally filter the result by Product using the `productId` query parameter.  The response includes monthly aggregate values, detailed request statistics, and quota limits used to monitor consumption and over-limit conditions.
     * @summary Get usage and quota
     * @param {string} organizationId The identifier of the Organization.
     * @param {string} [productId] The identifier of the Product to filter statistics for.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrganizationUsageAndQuota(organizationId: string, productId?: string, options?: RawAxiosRequestConfig) {
        return UsageQuotaApiFp(this.configuration).getOrganizationUsageAndQuota(organizationId, productId, options).then((request) => request(this.axios, this.basePath));
    }
}

